### ISSUE TITLE
Understand the functionality of Lucy’s converter

### ISSUE THREAD

**Issue by meenakshi-dhanani** [postmanlabs/api-spec-converter#11]
The goal of the spike: 
- Understand if we can build an API on top of Lucy converters so that we don't reinvent the wheel.
- Analyze which converters Lucy has
- Move the analysis to the wiki

**Comment by meenakshi-dhanani** [comment]
@pcgamer1 can you add all your learnings and analysis for Lucy as a comment here? so it stays here.

**Comment by meenakshi-dhanani** [comment]
https://docs.google.com/document/d/1o5KrhUYxRElGkZ5LmoMmey0WL_no5dsM7RiG3ExhY5M/edit?usp=sharing - link to the doc

**Comment by pcgamer1** [comment]
@meenakshi-dhanani I have updated the doc with my understanding about the converter.

**Comment by meenakshi-dhanani** [comment]
https://github.com/postmanlabs/api-spec-converter/wiki/Lucy's-Converter-Analysis - lgtm!
