### ISSUE TITLE
Add GSoC proposal to wiki

### ISSUE THREAD

**Issue by meenakshi-dhanani** [postmanlabs/api-spec-converter#16]
## Description
As a contributor,
I want to read through the proposal,
so that I can learn about the scope and initial plan of the project

### Update [Required]
- [x] Add proposal to wiki
- [x] Add list of tools/converters used for the PR raised during proposal phase

## Definition of Done
- [x] All of the required items are completed.
- [ ] Approval by 2 mentor.

**Comment by meenakshi-dhanani** [comment]
This isn't being worked upon right? Can we move it back to TODO then? @pcgamer1

**Comment by pcgamer1** [comment]
@meenakshi-dhanani added a wiki for the proposal - https://github.com/postmanlabs/api-spec-converter/wiki/Original-Proposal
