### ISSUE TITLE
Build project roadmap

### ISSUE THREAD

**Issue by AbhiramH** [postmanlabs/api-spec-converter#2]
Roadmap for next two months

### Acceptance Criteria: 
- [x] Create a wiki and add roadmap there from the doc

**Comment by pcgamer1** [comment]
https://docs.google.com/document/d/1nEJoHG-Fp3zRmKTauTNkKTlv0PXWkpLtGrUMhrxvwz4/edit?usp=sharing

**Comment by meenakshi-dhanani** [comment]
@pcgamer1 added acceptance criteria to add the roadmap from the doc to the wiki. Not a high priority but whenever you feel you're blocked because of other stuff, feel free to pick it up.

**Comment by pcgamer1** [comment]
@meenakshi-dhanani @AbhiramH updated the wiki.

**Comment by AbhiramH** [comment]
Mostly looks good to me. Are we using Lucy for OAS2 -> OAS3 conversion?

**Comment by pcgamer1** [comment]
@AbhiramH yeah, and I believe we will use it for other conversions as well after we are done with this one.

**Comment by meenakshi-dhanani** [comment]
https://github.com/postmanlabs/api-spec-converter/wiki/Project-Roadmap
